### ISSUE TITLE
Load Balancer Controller support

### ISSUE THREAD

**Issue by rothgar** [iplabs/terraform-kubernetes-alb-ingress-controller#10]
The v2 of the ALB ingress controller is now called the "Load Balancer Controller" would you be interested in a PR that supports the new controller. Is that work already being worked on?

Announcement blog post is up here https://aws.amazon.com/blogs/containers/introducing-aws-load-balancer-controller/

and example installation is here https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/installation/

**Comment by headcr4sh** [comment]
Hi @rothgar ,

the new AWS Load Balancer Controller is really interesting.
Installation via Terraform is a bit difficult right now, though.

Since the new controller relies on custom resource definitions (CRDs), the stable Terraform Kubernetes provider cannot be used to entirely bootstrap the installation in a reproducible manner. I think the new `kubernetes-alpha` Provider might solve these issues but I am not sure about the stability of the provider plugin, yet.

That said: yes. I am intereseted in the new controller.

**Comment by rothgar** [comment]
I came to the same conclusion yesterday digging into this problem. It's probably best to wait until the new terraform provider moves to stable (or at least beta) so CRDs will be support. I'll close this for now and will work on updating the LB controller docs repo.
